# Generated by Django 3.2 on 2022-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_category_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
